@if(auth()->user()->isAdmin())
    <x-admin-sidebar-layout>
        @include('dashboard.admin-dashboard')
    </x-admin-sidebar-layout>
@elseif(auth()->user()->isCook())
    <x-cook-sidebar-layout>
        @include('dashboard.chef-dashboard')
    </x-cook-sidebar-layout>
@else
    <x-client-sidebar-layout>
        @include('dashboard.client-dashboard')
    </x-client-sidebar-layout>
@endif
